version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: upana
      POSTGRES_DB: etldb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: upana@upana.edu.gt
      PGADMIN_DEFAULT_PASSWORD: upana
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: upana
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4
    command: redis-server --requirepass upana
    ports:
      - "6379:6379"
# docker exec -it tickets-redis-1 redis-cli -a upana

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:6379
      - REDIS_PASSWORD=upana
    ports:
      - "8081:8081"
    depends_on:
      - redis

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark:/opt/spark/work

  airflow:
    image: apache/airflow:2.9.0-python3.9
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow[postgres]
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:upana@postgres/etldb
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__AUTH_BACKENDS=airflow.providers.password.auth_backend.password_auth
    user: "airflow"  # Cambiar a usuario airflow en lugar de root
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@upana.com --password upana && airflow webserver"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8088:8080"
    depends_on:
      - postgres
      - redis

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data



  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: upana
      MYSQL_DATABASE: etldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: upana
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: upana
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3

  cassandra:
    image: cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: ETLCluster
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_PASSWORD: upana
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  jupyterNotebook:
      image: jupyter/pyspark-notebook
      depends_on:
        - spark
      ports:
        - "8888:8888"
      environment:
        - SPARK_MASTER=spark://spark:7077
        - JUPYTER_TOKEN=upana 
      volumes:
        - ./spark:/home/jovyan/work

volumes:
  pg_data:
  pgadmin_data:
  mongo_data:
  metabase_data:
  esdata:
  mariadb_data:
  arango_data:
  cassandra_data:
